### ISSUE TITLE
cannot module './config/multer' 문제

### ISSUE THREAD

**Issue by DotJM** [Hyun-juhee/nodejs-chatting#1]
git read me에 있는 모듈을 설치 했음에도, './config/multer'오류가 나는데 관련 자료를 찾기가 힘듭니다. 
혹시 이에 관한 조언을 들을 수 있을까요?

**Comment by c615615** [comment]
[nodejs]채팅에 multer s3부분생략된 코드를 부탁합니다 .

**Comment by mog-hi** [comment]
config/multer.js 파일 추가 업로드했습니다!
